font:
  normal:
    family: "JetbrainsMono Nerd Font Mono"
    style: Regular

  bold:
    family: "JetbrainsMono Nerd Font Mono"
    style: Bold

  italic:
    family: "JetbrainsMono Nerd Font Mono"
    style: Italic

  bold_italic:
    family: "JetbrainsMono Nerd Font Mono"
    style: Bold Italic

  size: 12

shell:
  program: /bin/zsh

colors:
  cursor:
      text: '0x665c54'
      cursor: '0xdfbf8e'

  primary:
    background: '0x282828'
    foreground: '0xdfbf8e'

  normal:
    black:   '0x665c54'
    red:     '0xea6962'
    green:   '0xa9b665'
    yellow:  '0xe78a4e'
    blue:    '0x7daea3'
    magenta: '0xd3869b'
    cyan:    '0x89b482'
    white:   '0xdfbf8e'

  bright:
    black:   '0x928374'
    red:     '0xea6962'
    green:   '0xa9b665'
    yellow:  '0xe3a84e'
    blue:    '0x7daea3'
    magenta: '0xd3869b'
    cyan:    '0x89b482'
    white:   '0xdfbf8e'

key_bindings:
  - { key: V, mods: Control, action: Paste } 
  - { key: V, mods: Control|Shift, action: ReceiveChar }
