font:
  normal:
    family: "Fira Code"
    style: Regular

  bold:
    family: "Fira Code"
    style: Regular

  italic:
    family: "Fira Code"
    style: Italic

  bold_italic:
    family: "Fira Code"
    style: Bold Italic

  size: 15

shell:
  program: /usr/local/bin/fish

colors:
  cursor:
      text: '0x665c54'
      cursor: '0xdfbf8e'

  primary:
    background: '0x282828'
    foreground: '0xdfbf8e'

  normal:
    black:   '0x665c54'
    red:     '0xea6962'
    green:   '0xa9b665'
    yellow:  '0xe78a4e'
    blue:    '0x7daea3'
    magenta: '0xd3869b'
    cyan:    '0x89b482'
    white:   '0xdfbf8e'

  bright:
    black:   '0x928374'
    red:     '0xea6962'
    green:   '0xa9b665'
    yellow:  '0xe3a84e'
    blue:    '0x7daea3'
    magenta: '0xd3869b'
    cyan:    '0x89b482'
    white:   '0xdfbf8e'

