local packer = require 'packer'

return packer.startup(function()
  use 'wbthomason/packer.nvim'

  use 'cappyzawa/starlark.vim'
  use 'fatih/vim-go'
  use 'hrsh7th/cmp-buffer'
  use 'hrsh7th/cmp-nvim-lsp'
  use 'hrsh7th/cmp-nvim-lua'
  use 'hrsh7th/nvim-cmp'
  use 'kyazdani42/nvim-web-devicons'
  use 'l3mon4d3/luasnip'
  use 'lewis6991/gitsigns.nvim'
  use 'morhetz/gruvbox'
  use 'neovim/nvim-lspconfig' 
  use 'nvim-lua/plenary.nvim'
  use 'nvim-lualine/lualine.nvim'
  use 'nvim-telescope/telescope-fzy-native.nvim'
  use 'nvim-telescope/telescope-project.nvim'
  use 'nvim-telescope/telescope.nvim'
  use 'nvim-treesitter/nvim-treesitter' 
  use 'nvim-treesitter/nvim-treesitter-textobjects'
  use 'nvim-treesitter/playground' 
  use 'prichrd/vim-matlab'
  use 'ray-x/lsp_signature.nvim'
  use 'rust-lang/rust.vim'
  use 'saadparwaiz1/cmp_luasnip'
  use 'theprimeagen/git-worktree.nvim'
  use 'tpope/vim-commentary'
  use 'tpope/vim-fugitive'
  use 'tpope/vim-surround'
  use 'tpope/vim-vinegar'
  use '~/Workspace/github.com/prichrd/snippets'
end)
