local packer = require 'packer'

return packer.startup(function()
  use 'wbthomason/packer.nvim'

  use 'fatih/vim-go'
  use 'habamax/vim-asciidoctor'
  use 'hrsh7th/cmp-buffer'
  use 'hrsh7th/cmp-nvim-lsp'
  use 'hrsh7th/cmp-vsnip'
  use 'hrsh7th/nvim-cmp'
  use 'hrsh7th/vim-vsnip'
  use 'hrsh7th/vim-vsnip-integ'
  use 'kristijanhusak/vim-dadbod-ui'
  use 'lewis6991/gitsigns.nvim'
  use 'maxmellon/vim-jsx-pretty'
  use 'morhetz/gruvbox'
  use 'neovim/nvim-lspconfig' 
  use 'nvim-lua/plenary.nvim'
  use 'nvim-telescope/telescope-fzy-native.nvim'
  use 'nvim-telescope/telescope-project.nvim'
  use 'nvim-telescope/telescope.nvim'
  use 'nvim-treesitter/nvim-treesitter' 
  use 'prichrd/vim-matlab'
  use 'rafamadriz/friendly-snippets'
  use 'ray-x/lsp_signature.nvim'
  use 'tpope/vim-commentary'
  use 'tpope/vim-dadbod'
  use 'tpope/vim-dispatch'
  use 'tpope/vim-dotenv'
  use 'tpope/vim-fugitive'
  use 'tpope/vim-surround'
  use 'tpope/vim-vinegar'
  use 'yuezk/vim-js'
end)
